elasticsearch_url: http://localhost:9200/geolife_one/group

find_by_term:
  "{
    \"query\": {
      \"bool\": {
        \"filter\": [
          {
            \"term\": {
              \"%s\": \"%s\"
            }
          }
        ]
      }
    },
    \"size\": 5000
  }"

find_by_user_id_and_by_hour_of_day:
  "{
     \"query\": {
       \"bool\": {
         \"must\": [
           {
             \"script\": {
               \"script\": \"doc['path.timestamp'].value.getHourOfDay() > %s && doc['path.timestamp'].value.getHourOfDay() < %s\"
             }
           },
           {
             \"term\": {
               \"userId.keyword\": {
                 \"value\": \"%s\"
               }
             }
           }
         ]
       }
     },
      \"size\": 5000
   }"