elasticsearch_url: http://localhost:9200/geolife_one/group

find_by_term:
  "{
    \"query\": {
      \"bool\": {
        \"filter\": [
          {
            \"term\": {
              \"%s\": \"%s\"
            }
          }
        ]
      }
    },
    \"size\": 5000
  }"
